[package]
name = "secrets-bin"
description = "Encrypt small packets of data into websafe text."
version = "0.2.0"
authors = ["Tim Shadel <tim@daylogger.com>"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "secrets"
path = "src/main.rs"

[dependencies]
exitfailure = "^0.5.1"
failure = "^0.1.5"
keyring = "^0.6.1"
serde_json = "^1.0"
simple-secrets = { path = "../lib" }
structopt = "^0.2"
