[package]
name = "secrets-wasm"
version = "0.2.0"
authors = ["Cameron Bytheway <bytheway.cameron@gmail.com>"]
edition = "2018"
private = true

[lib]
name = "simple_secrets"
crate-type = ["cdylib"]

[dependencies]
simple-secrets = { path = "../lib" }
wasm-bindgen = "0.2"
